table Fact_Subscriptions
	lineageTag: ce172144-c108-476e-8dc1-9efa27d6ebbe

	column 'Customer ID'
		dataType: string
		isHidden
		lineageTag: 0a5c6942-334d-487e-a992-4b6c0b4f1d3a
		summarizeBy: none
		sourceColumn: Customer ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Tenure Months'
		dataType: int64
		formatString: 0
		lineageTag: 0965114b-6e2e-4e59-ac08-6ffbff8a43b1
		summarizeBy: none
		sourceColumn: Tenure Months

		annotation SummarizationSetBy = User

	column 'Product Tier'
		dataType: string
		lineageTag: 33af80b6-4b61-41a1-8c43-5ac01b167a92
		summarizeBy: none
		sourceColumn: Product Tier

		annotation SummarizationSetBy = Automatic

	column 'Plan Type'
		dataType: string
		lineageTag: 068b3101-c210-4a72-a4b2-af9ed70c0165
		summarizeBy: none
		sourceColumn: Plan Type

		annotation SummarizationSetBy = Automatic

	column 'Paperless Billing'
		dataType: string
		lineageTag: 8c8ba23c-d3f1-4368-a0a5-2e00aa2a5a28
		summarizeBy: none
		sourceColumn: Paperless Billing

		annotation SummarizationSetBy = Automatic

	column 'Payment Method'
		dataType: string
		lineageTag: 6ebf842a-7512-4900-8842-807950fae9c1
		summarizeBy: none
		sourceColumn: Payment Method

		annotation SummarizationSetBy = Automatic

	column MRR
		dataType: double
		lineageTag: 0cd744d9-f945-4bfa-8c34-10909fba16a5
		summarizeBy: sum
		sourceColumn: MRR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Revenue'
		dataType: double
		lineageTag: 74fce1f2-dd20-4848-a54e-de8689889124
		summarizeBy: sum
		sourceColumn: Total Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Churned
		dataType: string
		lineageTag: 257ccdd9-c036-4491-ac45-058a1a2747cd
		summarizeBy: none
		sourceColumn: Churned

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Subscription Start Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 94be5fdf-cee5-43bc-83f2-f37b149bf086
		summarizeBy: none
		sourceColumn: Subscription Start Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start Month-Year'
		dataType: string
		lineageTag: 5ff9ca09-7de0-4219-8fd4-3cb3ae093709
		summarizeBy: none
		sourceColumn: Start Month-Year

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5c544ba8-0254-40a9-8764-c7ec3b306d10
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Feature Adoption Count'
		dataType: int64
		formatString: 0
		lineageTag: 85871de6-84cc-4220-ac6f-273ec1473bdd
		summarizeBy: none
		sourceColumn: Feature Adoption Count

		annotation SummarizationSetBy = User

	column 'Churn Flag'
		dataType: int64
		formatString: 0
		lineageTag: 99f4bc0a-fb47-4bfe-ae3e-307c23296662
		summarizeBy: sum
		sourceColumn: Churn Flag

		annotation SummarizationSetBy = Automatic

	column 'Tenure Bucket'
		dataType: string
		lineageTag: 3c3bc7ff-9ec8-44f4-b71f-44b6abb5c837
		summarizeBy: none
		sourceColumn: Tenure Bucket
		sortByColumn: 'tenure Bucket Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'tenure Bucket Sort'
		dataType: int64
		formatString: 0
		lineageTag: ce81fe22-97d2-4d33-b7ee-a08b9d3b6a64
		summarizeBy: sum
		sourceColumn: tenure Bucket Sort

		annotation SummarizationSetBy = Automatic

	partition Fact_Subscriptions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\power bi\saas-churn-analytics-dashboard\data\raw\WA_Fn-UseC_-Telco-Customer-Churn.csv"),[Delimiter=",", Columns=21, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customerID", type text}, {"gender", type text}, {"SeniorCitizen", Int64.Type}, {"Partner", type text}, {"Dependents", type text}, {"tenure", Int64.Type}, {"PhoneService", type text}, {"MultipleLines", type text}, {"InternetService", type text}, {"OnlineSecurity", type text}, {"OnlineBackup", type text}, {"DeviceProtection", type text}, {"TechSupport", type text}, {"StreamingTV", type text}, {"StreamingMovies", type text}, {"Contract", type text}, {"PaperlessBilling", type text}, {"PaymentMethod", type text}, {"MonthlyCharges", type number}, {"TotalCharges", type number}, {"Churn", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"gender", "SeniorCitizen", "Partner", "Dependents", "PhoneService", "MultipleLines"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "Feature Adoption Count", each (if [OnlineSecurity] = "Yes" then 1 else 0) +
				  (if [OnlineBackup] = "Yes" then 1 else 0) +
				  (if [DeviceProtection] = "Yes" then 1 else 0) +
				  (if [TechSupport] = "Yes" then 1 else 0) +
				  (if [StreamingTV] = "Yes" then 1 else 0) +
				  (if [StreamingMovies] = "Yes" then 1 else 0)),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom",{"OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns1",null,0,Replacer.ReplaceValue,{"TotalCharges"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"customerID", "Customer ID"}, {"tenure", "Tenure Months"}, {"InternetService", "Product Tier"}, {"Contract", "Plan Type"}, {"PaperlessBilling", "Paperless Billing"}, {"PaymentMethod", "Payment Method"}, {"MonthlyCharges", "MRR"}, {"TotalCharges", "Total Revenue"}, {"Churn", "Churned"}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Renamed Columns","Month-to-month","Monthly Plan",Replacer.ReplaceText,{"Plan Type"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","One year","Annual Plan",Replacer.ReplaceText,{"Plan Type"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Two year","Enterprise Plan",Replacer.ReplaceText,{"Plan Type"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","DSL","Basic Plan",Replacer.ReplaceText,{"Product Tier"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Fiber optic","Premium Plan",Replacer.ReplaceText,{"Product Tier"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","No","Free Tier",Replacer.ReplaceText,{"Product Tier"}),
				    #"Added Custom1" = Table.AddColumn(#"Replaced Value6", "Churn Flag", each if [Churned] = "Yes" then 1 else 0),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"Churn Flag", Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type1", "Tenure Bucket", each if [Tenure Months] <= 6 then "New  (0-6 months)" else if [Tenure Months] <= 12 then "Growing  (7-12 months)" else if [Tenure Months] <= 24 then "Established  (13-24 months)" else if [Tenure Months] <= 36 then "Loyal  (25-36 months)" else "Champion  ( 36+  months )"),
				    #"Added Custom2" = Table.AddColumn(#"Added Conditional Column", "Subscription Start Date", each Date.AddMonths(#date(2024, 12, 31), -[Tenure Months])),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom2",{{"Subscription Start Date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type2", "Year", each Date.Year([Subscription Start Date]), Int64.Type),
				    #"Added Custom3" = Table.AddColumn(#"Inserted Year", "Start Month-Year", each Date.ToText([Subscription Start Date], "MMM yyyy")),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom3",{"Customer ID", "Subscription Start Date", "Start Month-Year", "Year", "Tenure Months", "Product Tier", "Plan Type", "Paperless Billing", "Payment Method", "MRR", "Total Revenue", "Churned", "Feature Adoption Count", "Churn Flag", "Tenure Bucket"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Reordered Columns",{{"Start Month-Year", type text}, {"Tenure Bucket", type text}, {"Feature Adoption Count", Int64.Type}}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Changed Type3", "tenure Bucket Sort", each if [Tenure Bucket] = "New  (0-6 months)" then 1 else if [Tenure Bucket] = "Growing  (7-12 months)" then 2 else if [Tenure Bucket] = "Established  (13-24 months)" then 3 else if [Tenure Bucket] = "Loyal  (25-36 months)" then 4 else 5),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Conditional Column1",{{"tenure Bucket Sort", Int64.Type}})
				in
				    #"Changed Type4"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

